### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by lawrencemok** [greatfire/wiki#165]

**Comment by Crystal-RainSlide** [comment]
For what?
The Wall? Your patriotism? For GitHub?
If github is blocked for any reason, more  people will go access the Wall, and the Wall will be weaker for more guys going access it…
If the Wall didn't blocked Google, this project won't be here. 
It's all because of the Wall ,not the project contributors.
Ask the Wall unblock github when that happens, not issuing "please delete"here.

**Comment by soulofc** [comment]
@lawrencemok, please ask your mother go to my bed, because if if I don't fuck her tonight, I will rape her,  after that I will kill her. that is the logic same as your's, if don't let me fuck, i will rape.

**Comment by biuhahasdf** [comment]
满口生殖器 垃圾  @soulofc

**Comment by lawrencemok** [comment]
clam down guys, I just wanted to delete my own post......and couldn't find a way to do so
